
-- 创建国家表
CREATE TABLE IF NOT EXISTS countries (
    id INT AUTO_INCREMENT PRIMARY KEY,
    english_name VARCHAR(100) NOT NULL,
    chinese_name VARCHAR(100) NOT NULL,
    iso2_code CHAR(2),
    iso3_code CHAR(3),
    phone_code VARCHAR(10)
);

ALTER TABLE countries ADD UNIQUE (iso2_code);
ALTER TABLE countries ADD UNIQUE (english_name);
-- 插入国家数据
INSERT INTO countries (english_name, chinese_name, iso2_code, iso3_code, phone_code) VALUES
('Afghanistan', '阿富汗', 'AF', 'AFG', '93'),
('Albania', '阿尔巴尼亚', 'AL', 'ALB', '355'),
('Algeria', '阿尔及利亚', 'DZ', 'DZA', '213'),
('American Samoa', '美属萨摩亚', 'AS', 'ASM', '1-684'),
('Andorra', '安道尔', 'AD', 'AND', '376'),
('Angola', '安哥拉', 'AO', 'AGO', '244'),
('Anguilla', '安圭拉', 'AI', 'AIA', '1-264'),
('Antarctica', '南极洲', 'AQ', 'ATA', '672'),
('Antigua and Barbuda', '安提瓜和巴布达', 'AG', 'ATG', '1-268'),
('Argentina', '阿根廷', 'AR', 'ARG', '54'),
('Armenia', '亚美尼亚', 'AM', 'ARM', '374'),
('Aruba', '阿鲁巴', 'AW', 'ABW', '297'),
('Australia', '澳大利亚', 'AU', 'AUS', '61'),
('Austria', '奥地利', 'AT', 'AUT', '43'),
('Azerbaijan', '阿塞拜疆', 'AZ', 'AZE', '994'),
('Bahrain', '巴林', 'BH', 'BHR', '973'),
('Bangladesh', '孟加拉国', 'BD', 'BGD', '880'),
('Barbados', '巴巴多斯', 'BB', 'BRB', '1-246'),
('Belarus', '白俄罗斯', 'BY', 'BLR', '375'),
('Bermuda', '百慕大', 'BM', 'BMU', '1-441'),
('Bhutan', '不丹', 'BT', 'BTN', '975'),
('Bolivia', '玻利维亚', 'BO', 'BOL', '591'),
('Bonaire, Sint Eustatius and Saba', '荷兰加勒比区', 'BQ', 'BES', '599'),
('Bosnia and Herzegovina', '波黑', 'BA', 'BIH', '387'),
('Botswana', '博茨瓦纳', 'BW', 'BWA', '267'),
('Bouvet Island', '布韦岛', 'BV', 'BVT', '74'),
('Brazil', '巴西', 'BR', 'BRA', '55'),
('British Indian Ocean Territory', '英属印度洋领地', 'IO', 'IOT', '246'),
('Bulgaria', '保加利亚', 'BG', 'BGR', '359'),
('Burkina Faso', '布基纳法索', 'BF', 'BFA', '226'),
('Cambodia', '柬埔寨', 'KH', 'KHM', '855'),
('Cameroon', '喀麦隆', 'CM', 'CMR', '237'),
('Canada', '加拿大', 'CA', 'CAN', '1'),
('Cape Verde', '佛得角', 'CV', 'CPV', '238'),
('Cayman Islands', '开曼群岛', 'KY', 'CYM', '1-345'),
('Central African Republic', '中非共和国', 'CF', 'CAF', '236'),
('Chad', '乍得', 'TD', 'TCD', '235'),
('China', '中国', 'CN', 'CHN', '86'),
('Christmas Island', '圣诞岛', 'CX', 'CXR', '61'),
('Cocos (Keeling) Islands', '科科斯群岛', 'CC', 'CCK', '61'),
('Colombia', '哥伦比亚', 'CO', 'COL', '57'),
('Comoros', '科摩罗', 'KM', 'COM', '269'),
('Congo', '刚果', 'CG', 'COG', '242'),
('Cook Islands', '库克群岛', 'CK', 'COK', '682'),
('Costa Rica', '哥斯达黎加', 'CR', 'CRI', '506'),
('Croatia', '克罗地亚', 'HR', 'HRV', '385'),
('Cuba', '古巴', 'CU', 'CUB', '53'),
('Curacao', '库拉索', 'CW', 'CUW', '599'),
('Democratic Republic of the Congo', '刚果民主共和国', 'CD', 'COD', '243'),
('Denmark', '丹麦', 'DK', 'DNK', '45'),
('Dominica', '多米尼克', 'DM', 'DMA', '1-767'),
('Dominican Republic', '多明尼加共和国', 'DO', 'DOM', '1-809'),
('East Timor', '东帝汶', 'TL', 'TLS', '670'),
('Ecuador', '厄瓜多尔', 'EC', 'ECU', '593'),
('El Salvador', '萨尔瓦多', 'SV', 'SLV', '503'),
('Equatorial Guinea', '赤道几内亚', 'GQ', 'GNQ', '240'),
('Eritrea', '厄立特里亚', 'ER', 'ERI', '291'),
('Estonia', '爱沙尼亚', 'EE', 'EST', '372'),
('Ethiopia', '埃塞俄比亚', 'ET', 'ETH', '251'),
('Falkland Islands', '福克兰群岛', 'FK', 'FLK', '500'),
('Faroe Islands', '法罗群岛', 'FO', 'FRO', '298'),
('Finland', '芬兰', 'FI', 'FIN', '358'),
('France', '法国', 'FR', 'FRA', '33'),
('French Guiana', '法属圭亚那', 'GF', 'GUF', '594'),
('French Polynesia', '法属波利尼西亚', 'PF', 'PYF', '689'),
('Gabon', '加蓬', 'GA', 'GAB', '241'),
('Gambia', '冈比亚', 'GM', 'GMB', '220'),
('Georgia', '格鲁吉亚', 'GE', 'GEO', '995'),
('Germany', '德国', 'DE', 'DEU', '49'),
('Ghana', '加纳', 'GH', 'GHA', '233'),
('Gibraltar', '直布罗陀', 'GI', 'GIB', '350'),
('Greenland', '格陵兰', 'GL', 'GRL', '299'),
('Grenada', '格林纳达', 'GD', 'GRD', '1-473'),
('Guadeloupe', '瓜德罗普', 'GP', 'GLP', '590'),
('Guam', '关岛', 'GU', 'GUM', '1-671'),
('Guatemala', '危地马拉', 'GT', 'GTM', '502'),
('Guinea', '几内亚', 'GN', 'GIN', '224'),
('Guinea Bissau', '几内亚比绍', 'GW', 'GNB', '245'),
('Guyana', '圭亚那', 'GY', 'GUY', '592'),
('Haiti', '海地', 'HT', 'HTI', '509'),
('Heard Island and McDonald Islands', '赫德岛和麦克唐纳群岛', 'HM', 'HMD', '334'),
('Holy See (Vatican City State)', '梵蒂冈', 'VA', 'VAT', '379'),
('Honduras', '洪都拉斯', 'HN', 'HND', '504'),
('Hungary', '匈牙利', 'HU', 'HUN', '36'),
('Iceland', '冰岛', 'IS', 'ISL', '354'),
('India', '印度', 'IN', 'IND', '91'),
('Indonesia', '印尼', 'ID', 'IDN', '62'),
('Iran', '伊朗', 'IR', 'IRN', '98'),
('Iraq', '伊拉克', 'IQ', 'IRQ', '964'),
('Ireland', '爱尔兰', 'IE', 'IRL', '353'),
('Isle of Man', '马恩岛', 'IM', 'IMN', '44'),
('Israel', '以色列', 'IL', 'ISR', '972'),
('Italy', '意大利', 'IT', 'ITA', '39'),
('Jamaica', '牙买加', 'JM', 'JAM', '1-876'),
('Japan', '日本', 'JP', 'JPN', '81'),
('Jordan', '约旦', 'JO', 'JOR', '962'),
('Kazakhstan', '哈萨克斯坦', 'KZ', 'KAZ', '7'),
('Kenya', '肯尼亚', 'KE', 'KEN', '254'),
('Kiribati', '基里巴斯', 'KI', 'KIR', '686'),
('Kuwait', '科威特', 'KW', 'KWT', '965'),
('Kyrgyzstan', '吉尔吉斯斯坦', 'KG', 'KGZ', '996'),
('Landskapet Aland', '奥兰群岛', 'AX', 'ALA', '358'),
('Laos', '老挝', 'LA', 'LAO', '856'),
('Latvia', '拉脱维亚', 'LV', 'LVA', '371'),
('Lebanon', '黎巴嫩', 'LB', 'LBN', '961'),
('Liberia', '利比里亚', 'LR', 'LBR', '231'),
('Libya', '利比亚', 'LY', 'LBY', '218'),
('Lithuania', '立陶宛', 'LT', 'LTU', '370'),
('Macau', '中国澳门', 'MO', 'MAC', '853'),
('Macedonia', '马其顿', 'MK', 'MKD', '389'),
('Madagascar', '马达加斯加', 'MG', 'MDG', '261'),
('Malawi', '马拉维', 'MW', 'MWI', '265'),
('Malaysia', '马来西亚', 'MY', 'MYS', '60'),
('Maldives', '马尔代夫', 'MV', 'MDV', '960'),
('Mali', '马里', 'ML', 'MLI', '223'),
('Malta', '马耳他', 'MT', 'MLT', '356'),
('Marshall islands', '马绍尔群岛', 'MH', 'MHL', '692'),
('Martinique', '马提尼克', 'MQ', 'MTQ', '596'),
('Mauritania', '毛里塔尼亚', 'MR', 'MRT', '222'),
('Mauritius', '毛里求斯', 'MU', 'MUS', '230'),
('Mayotte', '马约特', 'YT', 'MYT', '262'),
('Micronesia (Federated States of)', '密克罗尼西亚联邦', 'FM', 'FSM', '691'),
('Moldova', '摩尔多瓦', 'MD', 'MDA', '373'),
('Monaco', '摩纳哥', 'MC', 'MCO', '377'),
('Mongolia', '蒙古', 'MN', 'MNG', '976'),
('Montserrat', '蒙塞拉特岛', 'MS', 'MSR', '1-664'),
('Mozambique', '莫桑比克', 'MZ', 'MOZ', '258'),
('Myanmar', '缅甸', 'MM', 'MMR', '95'),
('Nagorno-Karabakh', '纳戈尔诺-卡拉巴赫', NULL, NULL, '374'),
('Namibia', '纳米比亚', 'NA', 'NAM', '264'),
('Nauru', '瑙鲁', 'NR', 'NRU', '674'),
('Nepal', '尼泊尔', 'NP', 'NPL', '977'),
('Netherlands', '荷兰', 'NL', 'NLD', '31'),
('Netherlands Antilles', '荷属安的列斯群岛', 'AN', 'ANT', '599'),
('New Caledonia', '新喀里多尼亚', 'NC', 'NCL', '687'),
('New Zealand', '新西兰', 'NZ', 'NZL', '64'),
('Nicaragua', '尼加拉瓜', 'NI', 'NIC', '505'),
('Nigeria', '尼日利亚', 'NG', 'NGA', '234'),
('Norfolk Island', '诺福克岛', 'NF', 'NFK', '672'),
('North Korea', '北朝鲜', 'KP', 'PRK', '850'),
('Northern Mariana Islands', '北马里亚纳群岛', 'MP', 'MNP', '1-670'),
('Norway', '挪威', 'NO', 'NOR', '47'),
('Oman', '阿曼', 'OM', 'OMN', '968'),
('Pakistan', '巴基斯坦', 'PK', 'PAK', '92'),
('Palau', '帕劳', 'PW', 'PLW', '680'),
('Palestine, State of', '巴勒斯坦', 'PS', 'PSE', '970'),
('Panama', '巴拿马', 'PA', 'PAN', '507'),
('Papua New Guinea', '巴布亚新几内亚', 'PG', 'PNG', '675'),
('Paraguay', '巴拉圭', 'PY', 'PRY', '595'),
('Pitcairn Islands', '皮特凯恩群岛', 'PN', 'PCN', '64'),
('Poland', '波兰', 'PL', 'POL', '48'),
('Portugal', '葡萄牙', 'PT', 'PRT', '351'),
('Qatar', '卡塔尔', 'QA', 'QAT', '974'),
('Republic of Serbia', '塞尔维亚共和国', 'RS', 'SRB', '381'),
('Romania', '罗马尼亚', 'RO', 'ROU', '40'),
('Russia', '俄罗斯', 'RU', 'RUS', '7'),
('Rwanda', '卢旺达', 'RW', 'RWA', '250'),
('Saint Barthelemy', '圣巴泰勒米岛', 'BL', 'BLM', '590'),
('Saint Helena', '圣赫勒拿', 'SH', 'SHN', '290'),
('Saint Kitts and Nevis', '圣基茨和尼维斯', 'KN', 'KNA', '1-869'),
('Saint Lucia', '圣卢西亚', 'LC', 'LCA', '1-758'),
('Saint Martin (French part)', '法属圣马丁', 'MF', 'MAF', '590'),
('Saint Pierre and Miquelon', '圣皮埃尔和密克隆', 'PM', 'SPM', '508'),
('Saint Vincent and the Grenadines', '圣文森特和格林纳丁斯', 'VC', 'VCT', '1-784'),
('Samoa', '萨摩亚', 'WS', 'WSM', '685'),
('San Marino', '圣马力诺', 'SM', 'SMR', '378'),
('Sao Tome and Principe', '圣多美和普林西比', 'ST', 'STP', '239'),
('Saudi Arabia', '沙特阿拉伯', 'SA', 'SAU', '966'),
('Senegal', '塞内加尔', 'SN', 'SEN', '221'),
('Sierra Leone', '塞拉利昂', 'SL', 'SLE', '232'),
('Singapore', '新加坡', 'SG', 'SGP', '65'),
('Sint Maarten (Dutch part)', '荷属圣马丁', 'SX', 'SXM', '1-721'),
('Slovakia', '斯洛伐克', 'SK', 'SVK', '421'),
('Slovenia', '斯洛文尼亚', 'SI', 'SVN', '386'),
('Solomon Islands', '所罗门群岛', 'SB', 'SLB', '677'),
('Somalia', '索马里', 'SO', 'SOM', '252'),
('Somaliland', '索马里兰', NULL, NULL, '252'),
('South Africa', '南非', 'ZA', 'ZAF', '27'),
('South Georgia and South Sandwich Islands', '南乔治亚岛和南桑威奇群岛', 'GS', 'SGS', '500'),
('South Korea', '韩国', 'KR', 'KOR', '82'),
('South Sudan', '南苏丹', 'SS', 'SSD', '211'),
('Spain', '西班牙', 'ES', 'ESP', '34'),
('Sri Lanka', '斯里兰卡', 'LK', 'LKA', '94'),
('Sudan', '苏丹', 'SD', 'SDN', '249'),
('Suriname', '苏里南', 'SR', 'SUR', '597'),
('Svalbard and Jan Mayen', '斯瓦尔巴群岛和扬马延岛', 'SJ', 'SJM', '47'),
('Swaziland', '斯威士兰', 'SZ', 'SWZ', '268'),
('Switzerland', '瑞士', 'CH', 'CHE', '41'),
('Syria', '叙利亚', 'SY', 'SYR', '963'),
('Taiwan', '中国台湾', 'TW', 'TWN', '886'),
('Tajikistan', '塔吉克斯坦', 'TJ', 'TJK', '992'),
('Thailand', '泰国', 'TH', 'THA', '66'),
('The Bahamas', '巴哈马', 'BS', 'BHS', '1-242'),
('The Dominican Republic', '多米尼加共和国', 'DO', 'DOM', '1-809'),
('Tokelau', '托克劳', 'TK', 'TKL', '690'),
('Tonga', '汤加', 'TO', 'TON', '676'),
('Trinidad and Tobago', '特立尼达和多巴哥', 'TT', 'TTO', '1-868'),
('Tunisia', '突尼斯', 'TN', 'TUN', '216'),
('Turkmenistan', '土库曼斯坦', 'TM', 'TKM', '993'),
('Turks and Caicos Islands', '特克斯和凯科斯群岛', 'TC', 'TCA', '1-649'),
('Tuvalu', '图瓦卢', 'TV', 'TUV', '688'),
('Uganda', '乌干达', 'UG', 'UGA', '256'),
('Ukraine', '乌克兰', 'UA', 'UKR', '380'),
('United Arab Emirates', '阿联酋', 'AE', 'ARE', '971'),
('United Republic of Tanzania', '坦桑尼亚联合共和国', 'TZ', 'TZA', '255'),
('United States Minor Outlying Islands', '美国本土外小岛屿', 'UM', 'UMI', '246'),
('United States of America', '美国', 'US', 'USA', '1'),
('Uruguay', '乌拉圭', 'UY', 'URY', '598'),
('Uzbekistan', '乌兹别克斯坦', 'UZ', 'UZB', '998'),
('Vanuatu', '瓦努阿图', 'VU', 'VUT', '678'),
('Venezuela', '委内瑞拉', 'VE', 'VEN', '58'),
('Vietnam', '越南', 'VN', 'VNM', '84'),
('Virgin Islands (British)', '英属维尔京群岛', 'VG', 'VGB', '1-284'),
('Virgin Islands (U.S.)', '美属维尔京群岛', 'VI', 'VIR', '1-340'),
('Wallis and Futuna', '瓦利斯和富图纳', 'WF', 'WLF', '681'),
('Western Sahara', '西撒哈拉', 'EH', 'ESH', '212'),
('Yugoslavia', '南斯拉夫', 'YU', 'YUG', '381'),
('Zambia', '赞比亚', 'ZM', 'ZMB', '260'),
('Zimbabwe', '津巴布韦', 'ZW', 'ZWE', '263');